# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MealsRecipe' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MealsRecipe
  pod 'Alamofire'
  pod 'Kingfisher'

  target 'MealsRecipeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MealsRecipeUITests' do
    # Pods for testing
  end

end
